language: ruby
rvm:
  #- rbx
  - 2.2.5
  - 2.3.1
env:
  global:
    - SHOW_SIDEKIQ=true
  matrix:
    - SIDEKIQ_VERSION="~>4.2.0"
    - SIDEKIQ_VERSION="~>4.1.0"
    - SIDEKIQ_VERSION="~>4.0.2"
    - SIDEKIQ_VERSION="~>3.5.4"
    - SIDEKIQ_VERSION="~>3.4.2"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgmp3-dev
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle --version

script: bundle exec rake
services:
  - redis-server
